FROM python:3.11-slim

WORKDIR /app

COPY flask_app.py .
COPY client.py . 
COPY user_pb2.py .
COPY user_pb2_grpc.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "flask_app.py"]