FROM python:3.9-slim

WORKDIR /app

COPY alert_notifier_system.py requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8081

CMD ["python", "alert_notifier_system.py"]
