# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"[\n\x13RegisterUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x12\n\nhigh_value\x18\x03 \x01(\x02\x12\x11\n\tlow_value\x18\x04 \x01(\x02\"\"\n\x11\x44\x65leteUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"\x1d\n\x0c\x45mailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\".\n\x0e\x41verageRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"D\n\x0f\x41verageResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07\x61verage\x18\x03 \x01(\x02\"R\n\x0cUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\x02\",\n\x0bUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\"N\n\x16UpdateThresholdRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x12\n\nhigh_value\x18\x02 \x01(\x02\x12\x11\n\tlow_value\x18\x03 \x01(\x02\x32\xc6\x02\n\x0bUserService\x12\x33\n\x0cRegisterUser\x12\x14.RegisterUserRequest\x1a\r.UserResponse\x12/\n\x10UpdateUserTicker\x12\x0c.UserRequest\x1a\r.UserResponse\x12/\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\r.UserResponse\x12.\n\x0eGetLatestValue\x12\r.EmailRequest\x1a\r.UserResponse\x12\x35\n\x10\x43\x61lculateAverage\x12\x0f.AverageRequest\x1a\x10.AverageResponse\x12\x39\n\x0fUpdateThreshold\x12\x17.UpdateThresholdRequest\x1a\r.UserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERUSERREQUEST']._serialized_start=14
  _globals['_REGISTERUSERREQUEST']._serialized_end=105
  _globals['_DELETEUSERREQUEST']._serialized_start=107
  _globals['_DELETEUSERREQUEST']._serialized_end=141
  _globals['_EMAILREQUEST']._serialized_start=143
  _globals['_EMAILREQUEST']._serialized_end=172
  _globals['_AVERAGEREQUEST']._serialized_start=174
  _globals['_AVERAGEREQUEST']._serialized_end=220
  _globals['_AVERAGERESPONSE']._serialized_start=222
  _globals['_AVERAGERESPONSE']._serialized_end=290
  _globals['_USERRESPONSE']._serialized_start=292
  _globals['_USERRESPONSE']._serialized_end=374
  _globals['_USERREQUEST']._serialized_start=376
  _globals['_USERREQUEST']._serialized_end=420
  _globals['_UPDATETHRESHOLDREQUEST']._serialized_start=422
  _globals['_UPDATETHRESHOLDREQUEST']._serialized_end=500
  _globals['_USERSERVICE']._serialized_start=503
  _globals['_USERSERVICE']._serialized_end=829
# @@protoc_insertion_point(module_scope)
